steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        sudo apt update
        sudo apt-get install curl
        sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
        sudo apt -y install nodejs
        sudo node -v
        sudo npm config -g set strict-ssl false
        sudo npm install -g apiconnect -y
        sudo apic -v
    