steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        sudo apt update
        sudo uninstall -g nodejs
        # sudo curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
        # sudo sh ./setup_14.sh
        echo node version is
        sudo node -v
        echo npm version is 
        sudo npm -v
       # sudo npm config -g set strict-ssl false
       # sudo npm install --yes -g apiconnect
       # sudo apic -v
    