steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        sudo apt update
        sudo apt install nodejs
        sudo node -v
        sudo npm install apic
    