steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        sudo apt update
        sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
        sudo apt-get install -y nodejs
        echo node version is
        sudo node -v
        echo npm version is 
        sudo npm -v
        sudo npm config -g set strict-ssl false
        sudo echo y | npm install -g apiconnect
        sudo apic -v
    