steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        sudo apt update
        sudo rm -rf /usr/local/bin/npm /usr/local/share/man/man1/node* /usr/local/lib/dtrace/node.d ~/.npm ~/.node-gyp /opt/local/bin/node /opt/local/include/node /opt/local/lib/node_modules
        sudo rm -rf /usr/local/lib/node* 
        sudo rm -rf /usr/local/include/node*
        sudo rm -rf /usr/local/bin/node*
         
        sudo curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
        sudo sh ./setup_14.sh
        echo node version is
        sudo node -v
        echo npm version is 
        sudo npm -v
       # sudo npm config -g set strict-ssl false
       # sudo npm install --yes -g apiconnect
       # sudo apic -v
    