- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      sudo apt-get update
      sudo apt-get install docker
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      apt-get update
      apt-get install apiconnect